DESCRIPTION = "Advanced Enumerations (compatible with Python's stdlib Enum), NamedTuples, and NamedConstants"
SECTION = "devel/python"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://PKG-INFO;md5=798e5d1f0892eeada1fde204f2b6f607"

PYPI_PACKAGE = "aenum"
PYPI_PACKAGE_EXT = "tar.gz"
BBCLASSEXTEND = "native"

SRC_URI[md5sum] = "026786dbb37c15c2c8dc91fbf5828e97"
SRC_URI[sha256sum] = "a4334cabf47c167d44ab5a6198837b80deec5d5bad1b5cf70c966c3a330260e8"

inherit pypi